### ISSUE TITLE
sudo権限のないマシンへのRoot install, cmake error:"Could NOT find X11"

### ISSUE THREAD

**Issue by knegishi** [akira-okumura/RHEA#10]
sudo権限のないマシンへROOTをインストールしようとしています

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)

ROOT:root_v6.18.00.source

**問題**
cmakeが次のエラーで止まってしまいます。
`-- Looking for X11`
`CMake Error at /home1/eng-stf/knegishi/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):`
`  Could NOT find X11 (missing: X11_X11_INCLUDE_PATH X11_X11_LIB)
Call Stack (most recent call first):`
`  /home1/eng-stf/knegishi/local/share/cmake-3.15/Modules``/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)`
`  /home1/eng-stf/knegishi/local/share/cmake-3.15/Modules/FindX11.cmake:366 (find_package_handle_standard_args)`
`  cmake/modules/SearchInstalledSoftware.cmake:9 (_find_package)`
 ` cmake/modules/SearchInstalledSoftware.cmake:246 (find_package)`
`  CMakeLists.txt:159 (include)`
``
``
`-- Configuring incomplete, errors occurred!`

X11は既に動いていると思っています
`$ xdpyinfo`
`***`
`version number:    11.0`
`***`

**Comment by akira-okumura** [comment]
X11 を使った開発用の package が入っていないのだと思います。
```
$ yum list installed | grep X11
```
で `libX11-devel.x86_64` が表示されなければ、管理者に入れてもらうか、ユーザ権限の届く範囲の場所に入れるかだと思います。

**Comment by knegishi** [comment]
` yum list installed | grep X11`
`Repo rhel-7-server-rpms forced skip_if_unavailable=True due to: /etc/pki/entitlement/906548864024619442-key.pem`
`libX11.i686                          1.6.5-2.el7             @rhel-7-server-rpms`
`libX11.x86_64                        1.6.5-2.el7             @rhel-7-server-rpms`
`libX11-common.noarch                 1.6.5-2.el7             @rhel-7-server-rpms`

入っていないようでした。
今後の対応についてはもう少し考えます。
ありがとうございました。
