### ISSUE TITLE
ROOT 6.06.02ー起動時の問題

### ISSUE THREAD

**Issue by akiraasano** [akira-okumura/RHEA#5]
-問題点-
**ROOT  5.24.00**をmacにインストールした状態（正常に起動している）で、
**ROOT  6.06.02**を追加でインストールしてROOTを起動後、以下のエラーが表示された

<pre>
$root
**input_line_1:1:10: fatal error: file**
      '/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/new'
      modified since it was first processed
#include <new>
         ^
**input_line_3:38:10: fatal error: file**
      '/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/string'
      modified since it was first processed
#include &lt;string&gt;
         ^
   ----------------------------------------------------------------
  | Welcome to ROOT 6.06/02                    http://root.cern.ch |
  |                                   (c) 1995-2014, The ROOT Team |
  | Built for macosx64                                             |
  | From heads/master@v6-07-02-437-gb06340c, Mar 02 2016, 19:01:57 |
  | Try '.help', '.demo', '.license', '.credits', '.quit'/'.q'     |
   ----------------------------------------------------------------

**input_line_8:1:10: fatal error: file**
      '/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/iostream'
      modified since it was first processed
#include &lt;iostream&gt;
         ^
root [0] 
</pre>

**Comment by akira-okumura** [comment]
Xcode.app を立ち上げて、license が表示されたら agree してみてください。
