### ISSUE TITLE
makefileがあるのにmakeできない件 

### ISSUE THREAD

**Issue by satoken722** [akira-okumura/RHEA#6]
Linuxに ROOTをインストールしている最中に、configureの後にmakeできない

LinuxのOS ；Scientific Linux 7.1 

シェルの現状 ；
[sato.kenta@localhost root]$ ./configure
Enabled support for asimage, astiff, bonjour, builtin_afterimage, builtin_ftgl, builtin_llvm, explicitlink, fftw3, gviz, genvector, memstat, mysql, opengl, python, search_usrlocal, shadowpw, shared, ssl, tmva, vdt, x11, xft, xml.

To build ROOT type:

   make 

[sato.kenta@localhost root]$ make
make: **\* ターゲットがありません.  中止.
[sato.kenta@localhost root]$ ls
Makefile  config.log     fonts   icons        man         rootx
README    config.status  geom    include      math        sql
bin       configure      graf2d  interpreter  misc        test
bindings  core           graf3d  io           montecarlo  tmva
build     doc            gui     lib          net         tree
cmake     documentation  hist    macros       proof       tutorials
config    etc            html    main         roofit

現状；奥村pdfを参考にしつつ、Linuxにversion6.00.02をインストールしていた。./configure
          を実行して、makeを要求されたが、makefileがあるのにmakeと打っても実行できなかった。

今迄行ったこと ；https://root.cern.ch/build-prerequisites#fedora を見て、ビルドを行うと、./configureが最後まで実行できるようになり、上の図のシェルのようになった。 また、コンパイラもインストールした。
ビルド
 yum install git make gcc-c++ gcc binutils \
libX11-devel libXpm-devel libXft-devel libXext-devel

yum install gcc-gfortran openssl-devel pcre-devel \
mesa-libGL-devel mesa-libGLU-devel glew-devel ftgl-devel mysql-devel \
fftw-devel cfitsio-devel graphviz-devel \
avahi-compat-libdns_sd-devel libldap-dev python-devel \
libxml2-devel gsl-static
コンパイラ
 yum groupinstall 'Development Tools'

 yum install perl-ExtUtils-MakeMaker

 yum install gcc

**Comment by akira-okumura** [comment]
必要な library が存在しないのに configure が error を吐かないというのは、ROOT の configure が正しく記述されていないからだと思います (ROOT の問題)。恐らく ROOT 6.06/02 の configure では既に直っていると推測します。

**Comment by satoken722** [comment]
奥村先生
ROOT 6.06/02に変えるとmakeできました。
ありがとうございました。
